---
- hosts: all
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Create the container
      docker_container:
        name: webapp-container
        image: "nayakomprasad/webapp-avd:v1.0"
        state: started
        published_ports:
     # Publish container port 8080 as host port 8090
          - "0.0.0.0:8090:8080"
